//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package dagjson

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *Empty) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Empty) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Empty{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Empty: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Empty: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Empty: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Empty: string too large")
				}
				return fmt.Errorf("reading string for field Empty: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Empty: %w", err)
			}
			switch name {
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Empty: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Empty: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Empty")
			}
		}
	}

	return nil
}
func (t *Statement) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := false

	// t.Action (map[string]dagjson.Empty) (map)
	if len("Action") > 8192 {
		return fmt.Errorf("string in field \"Action\" was too long")
	}
	if err := jw.WriteString(string("Action")); err != nil {
		return fmt.Errorf("writing string for field \"Action\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Action) > 4096 {
			return fmt.Errorf("cannot marshal t.Action map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Action: %w", err)
		}

		keys := make([]string, 0, len(t.Action))
		for k := range t.Action {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Action: %w", err)
				}
			}
			v := t.Action[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Action: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Action: %w", err)
		}
	}

	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Effect (string) (string)
	if len("Effect") > 8192 {
		return fmt.Errorf("string in field \"Effect\" was too long")
	}
	if err := jw.WriteString(string("Effect")); err != nil {
		return fmt.Errorf("writing string for field \"Effect\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Effect) > 8192 {
		return fmt.Errorf("string in field t.Effect was too long")
	}
	if err := jw.WriteString(string(t.Effect)); err != nil {
		return fmt.Errorf("writing string for field t.Effect: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Principal (map[string]dagjson.Empty) (map)
	if len("Principal") > 8192 {
		return fmt.Errorf("string in field \"Principal\" was too long")
	}
	if err := jw.WriteString(string("Principal")); err != nil {
		return fmt.Errorf("writing string for field \"Principal\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Principal) > 4096 {
			return fmt.Errorf("cannot marshal t.Principal map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Principal: %w", err)
		}

		keys := make([]string, 0, len(t.Principal))
		for k := range t.Principal {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Principal: %w", err)
				}
			}
			v := t.Principal[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Principal: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Principal: %w", err)
		}
	}

	written = true
	if t.Sid != "" {
		if written {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Sid (string) (string)
	if t.Sid != "" {
		if len("Sid") > 8192 {
			return fmt.Errorf("string in field \"Sid\" was too long")
		}
		if err := jw.WriteString(string("Sid")); err != nil {
			return fmt.Errorf("writing string for field \"Sid\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if len(t.Sid) > 8192 {
			return fmt.Errorf("string in field t.Sid was too long")
		}
		if err := jw.WriteString(string(t.Sid)); err != nil {
			return fmt.Errorf("writing string for field t.Sid: %w", err)
		}
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Statement) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Statement{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Statement: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Statement: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Statement: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Statement: string too large")
				}
				return fmt.Errorf("reading string for field Statement: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Statement: %w", err)
			}
			switch name {

			// t.Action (map[string]dagjson.Empty) (map)
			case "Action":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Action: %w", err)
				}

				t.Action = map[string]Empty{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Action: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Action: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Action: %w", err)
						}
						var v Empty

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.Action[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Action: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.Effect (string) (string)
			case "Effect":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Effect: string too long")
						}
						return fmt.Errorf("reading string for field t.Effect: %w", err)
					}
					t.Effect = string(sval)
				}

				// t.Principal (map[string]dagjson.Empty) (map)
			case "Principal":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Principal: %w", err)
				}

				t.Principal = map[string]Empty{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Principal: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Principal: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Principal: %w", err)
						}
						var v Empty

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.Principal[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Principal: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.Sid (string) (string)
			case "Sid":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Sid: string too long")
						}
						return fmt.Errorf("reading string for field t.Sid: %w", err)
					}
					t.Sid = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Statement: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Statement: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Statement")
			}
		}
	}

	return nil
}
func (t *Policy) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Statement (map[string]dagjson.Empty) (map)
	if len("Statement") > 8192 {
		return fmt.Errorf("string in field \"Statement\" was too long")
	}
	if err := jw.WriteString(string("Statement")); err != nil {
		return fmt.Errorf("writing string for field \"Statement\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Statement) > 4096 {
			return fmt.Errorf("cannot marshal t.Statement map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Statement: %w", err)
		}

		keys := make([]string, 0, len(t.Statement))
		for k := range t.Statement {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Statement: %w", err)
				}
			}
			v := t.Statement[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Statement: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Statement: %w", err)
		}
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Policy) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Policy{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Policy: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Policy: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Policy: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Policy: string too large")
				}
				return fmt.Errorf("reading string for field Policy: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Policy: %w", err)
			}
			switch name {

			// t.Statement (map[string]dagjson.Empty) (map)
			case "Statement":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Statement: %w", err)
				}

				t.Statement = map[string]Empty{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Statement: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Statement: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Statement: %w", err)
						}
						var v Empty

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.Statement[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Statement: %w", err)
						}
						if close {
							break
						}
					}
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Policy: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Policy: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Policy")
			}
		}
	}

	return nil
}
