//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *BucketRegionMismatch) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := false

	// t.Actual (string) (string)
	if len("actual") > 8192 {
		return fmt.Errorf("string in field \"actual\" was too long")
	}
	if err := jw.WriteString(string("actual")); err != nil {
		return fmt.Errorf("writing string for field \"actual\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Actual) > 8192 {
		return fmt.Errorf("string in field t.Actual was too long")
	}
	if err := jw.WriteString(string(t.Actual)); err != nil {
		return fmt.Errorf("writing string for field t.Actual: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Expected (string) (string)
	if len("expected") > 8192 {
		return fmt.Errorf("string in field \"expected\" was too long")
	}
	if err := jw.WriteString(string("expected")); err != nil {
		return fmt.Errorf("writing string for field \"expected\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Expected) > 8192 {
		return fmt.Errorf("string in field t.Expected was too long")
	}
	if err := jw.WriteString(string(t.Expected)); err != nil {
		return fmt.Errorf("writing string for field t.Expected: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Message (string) (string)
	if len("message") > 8192 {
		return fmt.Errorf("string in field \"message\" was too long")
	}
	if err := jw.WriteString(string("message")); err != nil {
		return fmt.Errorf("writing string for field \"message\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Message) > 8192 {
		return fmt.Errorf("string in field t.Message was too long")
	}
	if err := jw.WriteString(string(t.Message)); err != nil {
		return fmt.Errorf("writing string for field t.Message: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Name (string) (string)
	if len("name") > 8192 {
		return fmt.Errorf("string in field \"name\" was too long")
	}
	if err := jw.WriteString(string("name")); err != nil {
		return fmt.Errorf("writing string for field \"name\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Name) > 8192 {
		return fmt.Errorf("string in field t.Name was too long")
	}
	if err := jw.WriteString(string(t.Name)); err != nil {
		return fmt.Errorf("writing string for field t.Name: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *BucketRegionMismatch) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = BucketRegionMismatch{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for BucketRegionMismatch: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for BucketRegionMismatch: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for BucketRegionMismatch: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field BucketRegionMismatch: string too large")
				}
				return fmt.Errorf("reading string for field BucketRegionMismatch: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field BucketRegionMismatch: %w", err)
			}
			switch name {

			// t.Actual (string) (string)
			case "actual":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Actual: string too long")
						}
						return fmt.Errorf("reading string for field t.Actual: %w", err)
					}
					t.Actual = string(sval)
				}

				// t.Expected (string) (string)
			case "expected":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Expected: string too long")
						}
						return fmt.Errorf("reading string for field t.Expected: %w", err)
					}
					t.Expected = string(sval)
				}

				// t.Message (string) (string)
			case "message":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Message: string too long")
						}
						return fmt.Errorf("reading string for field t.Message: %w", err)
					}
					t.Message = string(sval)
				}

				// t.Name (string) (string)
			case "name":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Name: string too long")
						}
						return fmt.Errorf("reading string for field t.Name: %w", err)
					}
					t.Name = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for BucketRegionMismatch: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field BucketRegionMismatch: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for BucketRegionMismatch")
			}
		}
	}

	return nil
}
